name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Validate Build Output
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Build artifacts:"
        ls -la dist/
        echo "📊 Build size:"
        du -sh dist/
        
    - name: Comment PR with build status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Build Successful!**
              
              🎉 Your Next.js Base Mini App has been built successfully!
              
              **Build Details:**
              - ✅ JavaScript compilation passed
              - ✅ Dependencies resolved
              - ✅ Production build created
              - ✅ All checks passed
              
              The app is ready for deployment when Vercel configuration is added.`
            });
          } catch (error) {
            console.log('Could not create PR comment:', error.message);
            console.log('✅ Build completed successfully anyway!');
          }
